services:
  # Backend Docker Web Service
  - type: web
    name: vaultx-backend
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: vaultx-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: vaultx-db
          property: port
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/securefiledb
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: vaultx-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: vaultx-db
          property: password
      - key: FILE_UPLOAD_DIR
        value: /tmp/uploads
      - key: JWT_SECRET
        generateValue: true

  # Frontend Static Site
  - type: web
    name: vaultx-frontend
    env: static
    buildCommand: ""
    staticPublishPath: ./frontend/src
    routes:
      - type: rewrite
        source: /api/*
        destination: https://vaultx-backend.onrender.com/api/*

databases:
  # Render Managed PostgreSQL Database
  - name: vaultx-db
    plan: free
    databaseName: securefiledb
    user: fileuser
