package com.securefile.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class DatabaseInitializer implements CommandLineRunner {

    private final JdbcTemplate jdbcTemplate;

    public DatabaseInitializer(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(String... args) {
        try {
            // Check if file_metadata table exists with user_id column
            Integer hasOldColumn = jdbcTemplate.queryForObject(
                "SELECT count(*) FROM information_schema.columns WHERE table_name = 'file_metadata' AND column_name = 'user_id'",
                Integer.class
            );

            if (hasOldColumn != null && hasOldColumn > 0) {
                jdbcTemplate.execute("DROP TABLE IF EXISTS file_metadata CASCADE");
                System.out.println("Dropped old file_metadata schema.");
            }

            // Always ensure file_metadata table exists with correct schema
            jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS file_metadata (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    original_filename VARCHAR(255) NOT NULL,
                    content_type VARCHAR(255) NOT NULL,
                    file_size BIGINT NOT NULL,
                    stored_path VARCHAR(255) NOT NULL,
                    encrypted_aes_key TEXT NOT NULL,
                    iv_base64 VARCHAR(255) NOT NULL,
                    sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    recipient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    uploaded_at TIMESTAMP NOT NULL
                )
            """);

            System.out.println(">>> Database Schema Initialized: file_metadata table ready!");

        } catch (Exception e) {
            System.err.println("Database initialization note: " + e.getMessage());
        }
    }
}
